version: 2.0
jobs:
 js_linting:
   docker:
     - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
   steps:
     - checkout # check out the code in the project directory
     - run: npm install
     - run: npx eslint src
 php_linting:
   docker:
     - image: cimg/php:8.0.3
   steps:
     - checkout # check out the code in the project directory
     - run: composer install
     - run: composer phpcs
workflows:
 version: 2
 basic_build_and_linting:
   jobs:
     - js_linting
     - php_linting