version: 2.0
jobs:
 js_scss_linting:
   docker:
    - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
   steps:
    - checkout # check out the code in the project directory
    - restore_cache:
        key: v1-dependency-cache-{{checksum "package-lock.json"}}
    - run: npm ci
    - save_cache:
        key: v1-dependency-cache-{{checksum "package-lock.json"}}
        paths:
          - node_modules
    - run: npx grunt test
 php_linting:
   docker:
    - image: cimg/php:7.4.19
      environment:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress
    - image: circleci/mysql:8.0.16
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: local
   working_directory: ~/php
   steps:
    - checkout # check out the code in the project directory
    - run:
        name: Install PHP exts
        command: |
          curl -o setup-phpunit.sh https://gist.githubusercontent.com/keesiemeijer/a888f3d9609478b310c2d952644891ba/raw/
          pwd
          ls -a
          cd $HOME
          ls -a
          cd /home/circleci/php
          sudo bash ./setup-phpunit.sh
    - restore_cache:
        key: -v1-deps{{checksum "composer.lock"}}
    - run: composer install
    - save_cache:
        key: -v1-deps{{checksum "composer.lock"}}
        paths:
          - vendor
    - run: composer phpcs
workflows:
 version: 2
 basic_linting_tests:
   jobs:
    - js_scss_linting
    - php_linting